name: url_update
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: bash url_update.sh
      run: |
        chmod +x url_update.sh
        bash url_update.sh
        cat index.html
        echo "----------  finish -----------"
    - name: set git config 
      run: |
        git config --global user.name "Xiechengqi"
        git config --global user.email "Xiechengqi01@gmail.com"
    - name: add ssh primary key
      run: |
        mkdir /home/runner/.ssh/
        echo "${{ secrets.SSH_PRIVATE_KEY }}">/home/runner/.ssh/id_rsa 
        chmod 600 /home/runner/.ssh/id_rsa
        ssh-keyscan -t rsa "github.com">>/home/runner/.ssh/known_hosts
    - name: deploy
      run: |
        echo "--------- log start -----------"
        git log --pretty=format:"%s from Github Actions at `date +"%Y-%m-%d %H:%M:%S"`" --date=short -n 1  > commit-message.log
    - name: deploy
      run: |
        echo "------------ git clone start ------------"
        git clone git@github.com:Xiechengqi/test.git .test
        cd .test
        git checkout master
        cd ../
        \cp -rf ./* ./.test/
        cd .test
        rm commit-message.log -rf
        git add .
        git commit -F ../commit-message.log
        git push --force --quiet "git@github.com:Xiechengqi/test.git" master:master
